name: FIX Coding

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install composer packages
        run: composer install

      - name: Run Fixer
        run: composer run csfix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
